[package]
name = "faxtop"
version = "0.0.1"
authors = ["metastasis <metastasis@protonmail.ch>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
